import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.scss';
import StoreProvider from './store-provider';
import { fetchFromAPI } from '@/utils/api';

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-mona-sans',
});

export async function generateMetadata(): Promise<Metadata> {
  const siteSettings = await fetchFromAPI('/api/settings/site');

  return {
    title: siteSettings?.title || 'Togeto - Transport & Logistics',
    description: siteSettings?.description || 'Generated by create next app',
    icons: {
      icon: siteSettings?.faviconUrl || '/favicon.ico',
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakartaSans.variable} suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
