import type { Metadata } from 'next';
import './globals.scss';
import StoreProvider from './store-provider';

export const metadata: Metadata = {
  title: 'Togelo - Transport & Logistics Next Js Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
